apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-claim
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40G
